/* Main.ino file generated by New Project wizard
 *
 * Created:   ¬т мар 5 2024
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR
 */

#define PB0 8


	  // the setup function runs once when you press reset or power the board
void setup() {
	  // initialize digital pin LED_BUILTIN as an output.
	  pinMode(LED_BUILTIN, OUTPUT);
	  pinMode(PB0, OUTPUT);

}

// the loop function runs over and over again forever
void loop() {
	  digitalWrite(LED_BUILTIN, HIGH);  // turn the LED on (HIGH is the voltage level)
	  digitalWrite(PB0, LOW);  		// turn the LED on (HIGH is the voltage level)
	  delay(1000);                      // wait for a second
	  digitalWrite(LED_BUILTIN, LOW);   // turn the LED off by making the voltage LOW
	  digitalWrite(PB0, HIGH);  		// turn the LED on (HIGH is the voltage level)
	  delay(1000);                      // wait for a second
}
